### ISSUE TITLE
[ZMIANA] Podgląd rezerwacji po stronie klienta 

### ISSUE THREAD

**Issue by Michalski-Artur** [pw-software-engineering/specification#24]
Endpoint do podglądu rezerwacji po stronie klienta zwraca obecnie następujące dane: 
```yaml
[
                  {
                    "hotelInfoPreview": {
                      "hotelID": int,
                      "hotelName": string,
                      "country": string,
                      "city": string
                    },
                    "offerReservations": {
                      "reservationsInfo": [
                        {
                          "reservationID": int,
                          "from": datetime,
                          "to": datetime,
                          "numberOfChildren": int,
                          "numberOfAdults": int
                        }
                      ],
                      "offerID": int,
                      "offerReviewID": int? (optional - not present if there is no client review for an offer),
                    }
                  }
                ]
```
Chcemy dodać więcej informacji o ofercie. Konkretnie cały obiekt offerInfoPreview:
```yaml
"offerInfoPreview": {
                        "offerID": int,
                        "offerReviewID": int? (optional - not present if there is no client review for an offer),
                        "offerPreviewPicture": file,
                        "offerTitle": string
                      }
``` 
Zwracamy offerPreviewPicture i offerTitle aby klient łatwiej mógł ją zidentyfikować. Mamy co prawda offerID, ale zwrócenie obiektu oferty wymaga skorzystanie z endpointu: `/hotels/{hotelID}/offers/{offerID}`
Ostatecznie endpoint zwracałby taki obiekt:
```yaml
[
                  {
                    "hotelInfoPreview": {
                      "hotelID": int,
                      "hotelName": string,
                      "country": string,
                      "city": string
                    },
                    "offerReservations": {
                      "reservationsInfo": [
                        {
                          "reservationID": int,
                          "from": datetime,
                          "to": datetime,
                          "numberOfChildren": int,
                          "numberOfAdults": int
                        }
                      ],
                      "offerInfoPreview": {
                        "offerID": int,
                        "offerReviewID": int? (optional - not present if there is no client review for an offer),
                        "offerPicturePreview": file,
                        "offerTitle": string
                      }
                    }
                  }
                ]
```
