### ISSUE TITLE
[ZMIANA] Paging rezerwacji po stronie klienta 

### ISSUE THREAD

**Issue by Michalski-Artur** [pw-software-engineering/specification#25]
Klient może mieć potencjalnie wiele rezerwacji. W celu zwiększenia czytelności chcemy dodać paging do rezerwacji.
```yaml
 /reservations:
    get:
    is: [pageable]
      description: Get list of all reservations made by the client
```
